// Generated by CoffeeScript 1.9.3
(function() {
  SC.initialize({
    client_id: "41070595af5b644554785b5be6645060"
  });

  $(document).ready(function() {
    return SC.get('/tracks', {
      genres: 'rap'
    }, function(tracks) {
      return $(tracks).each(function(index, track) {
        return $('#results').append($('<li></li>').html(track.title + ' - ' + track.genre));
      });
    });
  });

}).call(this);
