// Generated by CoffeeScript 1.7.1
(function() {
  SC.initialize({
    client_id: "41070595af5b644554785b5be6645060"
  });

  $(document).ready(function() {
    return SC.stream('/tracks/290', function(sound) {
      return sound.load({
        stream: false,
        onload: function() {
          var timestamp;
          console.log("before playing");
          this.play();
          console.log("after playing");
          timestamp = performance.now();
          console.log("after getting time");
          console.log(timestamp);
        }
      });
    });
  });

}).call(this);
