// Generated by CoffeeScript 1.9.3
(function() {
  SC.initialize({
    client_id: "41070595af5b644554785b5be6645060"
  });

  $(document).ready(function() {
	  SC.get('/tracks', { genres: 'rap' }, function(tracks) {
	    $(tracks).each(function(index, track) {
	      $('#results').append($('<li></li>').html(track.title + ' - ' + track.genre));
	    });
	  });
	});

}).call(this);
