// Generated by CoffeeScript 1.9.3
SC.initialize({
  client_id: "41070595af5b644554785b5be6645060"
});

$(document).ready(function() {
  return SC.stream('/tracks/290', function(sound) {
    return $('#start').click(function(e) {
      return sound.start();
    });
  });
});
